# Generated by Django 5.2.17 on 2026-08-11 21:04

import apps.live.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('videos', '0002_video_search_vector_video_video_search_vector_gin'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(help_text="Identifiant public du direct. Apparait dans l'URL HLS: il ne doit jamais contenir la cle de flux.", max_length=40, unique=True)),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='titre')),
                ('description', models.TextField(blank=True, max_length=2000, verbose_name='description')),
                ('stream_key', models.CharField(default=apps.live.models.generate_stream_key, editable=False, help_text="Secret. Jamais expose a personne d'autre que le proprietaire.", max_length=64, unique=True)),
                ('stream_key_rotated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('offline', 'Hors ligne'), ('live', 'En direct'), ('ended', 'Termine')], db_index=True, default='offline', max_length=10)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('current_viewer_count', models.PositiveIntegerField(default=0)),
                ('peak_viewer_count', models.PositiveIntegerField(default=0, help_text='Pic sur la session en cours ou la derniere session.')),
                ('all_time_peak_viewers', models.PositiveIntegerField(default=0)),
                ('total_sessions', models.PositiveIntegerField(default=0)),
                ('is_enabled', models.BooleanField(db_index=True, default=True, help_text='Decoche par un moderateur pour bloquer toute nouvelle diffusion sans supprimer la chaine.')),
                ('chat_enabled', models.BooleanField(default=True)),
                ('record_sessions', models.BooleanField(default=True, help_text="Convertit l'enregistrement en video a la fin du direct.")),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='live_channels', to='catalog.category')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='live_channel', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'chaine en direct',
                'verbose_name_plural': 'chaines en direct',
                'ordering': ('-started_at', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='LiveRecording',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('peak_viewer_count', models.PositiveIntegerField(default=0)),
                ('chat_message_count', models.PositiveIntegerField(default=0)),
                ('recorded_file', models.CharField(blank=True, max_length=512)),
                ('recorded_size_bytes', models.BigIntegerField(default=0)),
                ('conversion_error', models.TextField(blank=True)),
                ('converted_video', models.ForeignKey(blank=True, help_text="Renseigne une fois l'enregistrement passe par le pipeline VOD.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_live_recording', to='videos.video')),
                ('live_channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recordings', to='live.livechannel')),
            ],
            options={
                'verbose_name': 'session en direct',
                'verbose_name_plural': 'sessions en direct',
                'ordering': ('-started_at',),
            },
        ),
        migrations.CreateModel(
            name='LiveChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=500)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_live_messages', to=settings.AUTH_USER_MODEL)),
                ('live_channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='live.livechannel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_messages', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='live.liverecording')),
            ],
            options={
                'verbose_name': 'message de chat',
                'verbose_name_plural': 'messages de chat',
                'ordering': ('created_at',),
            },
        ),
        migrations.AddIndex(
            model_name='livechannel',
            index=models.Index(fields=['status', '-started_at'], name='live_livech_status_c289ff_idx'),
        ),
        migrations.AddIndex(
            model_name='liverecording',
            index=models.Index(fields=['live_channel', '-started_at'], name='live_livere_live_ch_25b829_idx'),
        ),
        migrations.AddIndex(
            model_name='livechatmessage',
            index=models.Index(fields=['live_channel', '-created_at'], name='live_livech_live_ch_b7b53b_idx'),
        ),
        migrations.AddIndex(
            model_name='livechatmessage',
            index=models.Index(fields=['session', 'created_at'], name='live_livech_session_469470_idx'),
        ),
    ]
