# Generated by Django 5.2.17 on 2026-08-11 19:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('videos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content', models.TextField(max_length=2000)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deletion_reason', models.TextField(blank=True)),
                ('reply_count', models.PositiveIntegerField(default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_comments', to=settings.AUTH_USER_MODEL)),
                ('parent_comment', models.ForeignKey(blank=True, help_text='Un seul niveau de reponse: une reponse ne peut pas avoir elle-meme de parent.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='engagement.comment')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='videos.video')),
            ],
            options={
                'verbose_name': 'commentaire',
                'verbose_name_plural': 'commentaires',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['video', 'parent_comment', '-created_at'], name='engagement__video_i_c59225_idx'), models.Index(fields=['author', '-created_at'], name='engagement__author__f75885_idx')],
            },
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_like', models.BooleanField(help_text="True = j'aime, False = je n'aime pas.")),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='videos.video')),
            ],
            options={
                'verbose_name': 'appreciation',
                'verbose_name_plural': 'appreciations',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['video', 'is_like'], name='engagement__video_i_7c6f87_idx')],
                'constraints': [models.UniqueConstraint(fields=('video', 'user'), name='uniq_like_per_video_user')],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('object_id', models.CharField(db_index=True, max_length=64)),
                ('reason', models.CharField(choices=[('spam', 'Spam ou contenu trompeur'), ('harassment', 'Harcelement ou haine'), ('violence', 'Violence ou contenu choquant'), ('sexual', 'Contenu sexuel'), ('copyright', "Violation de droits d'auteur"), ('misinformation', 'Desinformation'), ('other', 'Autre')], max_length=24)),
                ('details', models.TextField(blank=True, max_length=1000)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('actioned', 'Traite'), ('dismissed', 'Rejete')], db_index=True, default='pending', max_length=12)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_note', models.TextField(blank=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_filed', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_reviewed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'signalement',
                'verbose_name_plural': 'signalements',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['status', '-created_at'], name='engagement__status_3f44d9_idx'), models.Index(fields=['content_type', 'object_id'], name='engagement__content_e3eb24_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('reporter', 'content_type', 'object_id'), name='uniq_pending_report_per_reporter_target')],
            },
        ),
        migrations.CreateModel(
            name='View',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, max_length=64)),
                ('ip_hash', models.CharField(blank=True, help_text="SHA-256 sale de l'IP. L'IP brute n'est jamais stockee.", max_length=64)),
                ('watched_seconds', models.PositiveIntegerField(default=0)),
                ('counted', models.BooleanField(db_index=True, default=False, help_text='Passe a True quand la duree minimale est atteinte.')),
                ('dedup_key', models.CharField(db_index=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='videos.video')),
                ('viewer', models.ForeignKey(blank=True, help_text='Null pour les visiteurs anonymes.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='views', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'vue',
                'verbose_name_plural': 'vues',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['video', 'counted', '-created_at'], name='engagement__video_i_76c6f1_idx'), models.Index(fields=['viewer', '-created_at'], name='engagement__viewer__fc3c38_idx')],
                'constraints': [models.UniqueConstraint(fields=('video', 'dedup_key'), name='uniq_view_per_video_dedup_key')],
            },
        ),
    ]
