# Generated by Django 5.2.17 on 2026-08-11 15:28

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='titre')),
                ('description', models.TextField(blank=True, max_length=5000, verbose_name='description')),
                ('status', models.CharField(choices=[('processing', 'En traitement'), ('ready', 'Prete'), ('failed', 'Echec'), ('taken_down', 'Retiree')], db_index=True, default='processing', max_length=16)),
                ('visibility', models.CharField(choices=[('public', 'Publique'), ('unlisted', 'Non repertoriee'), ('private', 'Privee')], db_index=True, default='private', help_text="Par defaut privee: rien n'est publie tant que l'auteur n'a pas explicitement choisi de publier.", max_length=16)),
                ('duration_seconds', models.PositiveIntegerField(db_index=True, default=0)),
                ('source_width', models.PositiveIntegerField(default=0)),
                ('source_height', models.PositiveIntegerField(default=0)),
                ('source_resolution', models.CharField(blank=True, max_length=20)),
                ('source_video_codec', models.CharField(blank=True, max_length=40)),
                ('source_audio_codec', models.CharField(blank=True, max_length=40)),
                ('has_audio', models.BooleanField(default=True)),
                ('original_key', models.CharField(blank=True, max_length=512)),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('original_size_bytes', models.BigIntegerField(default=0)),
                ('original_mime_type', models.CharField(blank=True, max_length=100)),
                ('storage_bucket', models.CharField(blank=True, help_text='Bucket ou vivent actuellement les rendus HLS. Change quand la visibilite bascule prive <-> public.', max_length=100)),
                ('hls_master_path', models.CharField(blank=True, max_length=512)),
                ('poster_path', models.CharField(blank=True, max_length=512)),
                ('sprite_path', models.CharField(blank=True, max_length=512)),
                ('thumbnail_vtt_path', models.CharField(blank=True, max_length=512)),
                ('sprite_meta', models.JSONField(blank=True, default=dict, help_text="Geometrie de la planche de miniatures (colonnes, lignes, taille de tuile, intervalle). Le lecteur calcule les decalages a partir de ces valeurs, ce qui fonctionne a l'identique pour les URLs publiques et presignees.")),
                ('processing_stage', models.CharField(choices=[('queued', "En file d'attente"), ('probing', 'Analyse du fichier'), ('transcoding', 'Transcodage'), ('packaging', 'Assemblage du manifeste'), ('thumbnails', 'Generation des miniatures'), ('publishing', 'Publication'), ('done', 'Termine')], default='queued', max_length=20)),
                ('processing_progress', models.PositiveSmallIntegerField(default=0, help_text='0-100, tous stades confondus.')),
                ('failure_reason', models.TextField(blank=True)),
                ('transcode_attempts', models.PositiveSmallIntegerField(default=0)),
                ('view_count', models.PositiveIntegerField(db_index=True, default=0)),
                ('like_count', models.PositiveIntegerField(default=0)),
                ('dislike_count', models.PositiveIntegerField(default=0)),
                ('comment_count', models.PositiveIntegerField(default=0)),
                ('takedown_reason', models.TextField(blank=True)),
                ('taken_down_at', models.DateTimeField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('published_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='videos', to='catalog.category')),
                ('tags', models.ManyToManyField(blank=True, related_name='videos', to='catalog.tag')),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'video',
                'verbose_name_plural': 'videos',
                'ordering': ('-uploaded_at',),
            },
        ),
        migrations.CreateModel(
            name='UploadSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('filename', models.CharField(max_length=255)),
                ('upload_length', models.BigIntegerField(help_text='Taille annoncee, en octets.')),
                ('offset', models.BigIntegerField(default=0)),
                ('status', models.CharField(choices=[('in_progress', 'Televersement en cours'), ('completed', 'Televersement termine'), ('aborted', 'Abandonne'), ('expired', 'Expire')], db_index=True, default='in_progress', max_length=16)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('scratch_path', models.CharField(max_length=512)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upload_sessions', to=settings.AUTH_USER_MODEL)),
                ('video', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='upload_session', to='videos.video')),
            ],
            options={
                'verbose_name': 'session de televersement',
                'verbose_name_plural': 'sessions de televersement',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='VideoRendition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='240p, 360p, 480p, 720p, 1080p', max_length=10)),
                ('width', models.PositiveIntegerField()),
                ('height', models.PositiveIntegerField()),
                ('video_bitrate_kbps', models.PositiveIntegerField()),
                ('audio_bitrate_kbps', models.PositiveIntegerField(default=128)),
                ('hls_playlist_path', models.CharField(max_length=512)),
                ('file_size', models.BigIntegerField(default=0)),
                ('segment_count', models.PositiveIntegerField(default=0)),
                ('codecs', models.CharField(blank=True, help_text='RFC 6381 string used in the master playlist.', max_length=60)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renditions', to='videos.video')),
            ],
            options={
                'verbose_name': 'rendu video',
                'verbose_name_plural': 'rendus video',
                'ordering': ('height',),
            },
        ),
        migrations.CreateModel(
            name='VideoThumbnail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp_offset', models.FloatField(default=0, help_text='Secondes depuis le debut.')),
                ('image_path', models.CharField(max_length=512)),
                ('is_poster', models.BooleanField(db_index=True, default=False)),
                ('sprite_x', models.PositiveIntegerField(blank=True, null=True)),
                ('sprite_y', models.PositiveIntegerField(blank=True, null=True)),
                ('sprite_width', models.PositiveIntegerField(blank=True, null=True)),
                ('sprite_height', models.PositiveIntegerField(blank=True, null=True)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thumbnails', to='videos.video')),
            ],
            options={
                'verbose_name': 'miniature',
                'verbose_name_plural': 'miniatures',
                'ordering': ('timestamp_offset',),
            },
        ),
        migrations.AddIndex(
            model_name='video',
            index=models.Index(fields=['status', 'visibility', '-published_at'], name='videos_vide_status_8ef0ac_idx'),
        ),
        migrations.AddIndex(
            model_name='video',
            index=models.Index(fields=['uploader', '-uploaded_at'], name='videos_vide_uploade_4de473_idx'),
        ),
        migrations.AddIndex(
            model_name='video',
            index=models.Index(fields=['-view_count'], name='videos_vide_view_co_02bc14_idx'),
        ),
        migrations.AddConstraint(
            model_name='videorendition',
            constraint=models.UniqueConstraint(fields=('video', 'label'), name='uniq_rendition_per_video_label'),
        ),
        migrations.AddIndex(
            model_name='videothumbnail',
            index=models.Index(fields=['video', 'timestamp_offset'], name='videos_vide_video_i_03ea7e_idx'),
        ),
    ]
