# Generated by Django 5.2.17 on 2026-08-12 07:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('videos', '0002_video_search_vector_video_video_search_vector_gin'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='is_short',
            field=models.BooleanField(db_index=True, default=False, help_text="Format court vertical. Derive automatiquement de la duree et du ratio de la source au moment du transcodage — jamais saisi a la main, pour qu'une video ne puisse pas se declarer short et court-circuiter le fil principal."),
        ),
        migrations.AddIndex(
            model_name='video',
            index=models.Index(fields=['is_short', 'status', 'visibility', '-published_at'], name='video_shorts_feed_idx'),
        ),
    ]
