# Generated by Django 5.2.17 on 2026-08-11 15:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('video.uploaded', 'Video televersee'), ('video.updated', 'Video modifiee'), ('video.deleted', 'Video supprimee'), ('video.visibility_changed', 'Visibilite modifiee'), ('video.transcode_retried', 'Transcodage relance'), ('video.taken_down', 'Video retiree'), ('user.suspended', 'Compte suspendu'), ('user.unsuspended', 'Suspension levee'), ('user.role_changed', 'Role modifie'), ('report.reviewed', 'Signalement traite'), ('campaign.changed', 'Campagne publicitaire modifiee'), ('payment.event', 'Evenement de paiement')], db_index=True, max_length=64)),
                ('object_id', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('object_repr', models.CharField(blank=True, max_length=255)),
                ('reason', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, help_text='Null pour les actions systeme (taches Celery).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_entries', to=settings.AUTH_USER_MODEL)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': "entree d'audit",
                'verbose_name_plural': "journal d'audit",
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['action', '-created_at'], name='audit_audit_action_0c6a84_idx'), models.Index(fields=['content_type', 'object_id'], name='audit_audit_content_4c2ead_idx')],
            },
        ),
    ]
