# Generated by Django 5.2.17 on 2026-08-11 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('video.uploaded', 'Video televersee'), ('video.updated', 'Video modifiee'), ('video.deleted', 'Video supprimee'), ('video.visibility_changed', 'Visibilite modifiee'), ('video.transcode_retried', 'Transcodage relance'), ('video.taken_down', 'Video retiree'), ('user.suspended', 'Compte suspendu'), ('user.unsuspended', 'Suspension levee'), ('user.role_changed', 'Role modifie'), ('comment.removed', 'Commentaire supprime'), ('report.reviewed', 'Signalement traite'), ('campaign.changed', 'Campagne publicitaire modifiee'), ('payment.event', 'Evenement de paiement')], db_index=True, max_length=64),
        ),
    ]
