# Generated by Django 5.2.17 on 2026-08-11 23:31

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('engagement', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModerationAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(choices=[('video_taken_down', 'Video retiree'), ('video_restored', 'Video retablie'), ('comment_removed', 'Commentaire supprime'), ('report_dismissed', 'Signalement rejete'), ('user_warned', 'Utilisateur averti'), ('user_suspended', 'Utilisateur suspendu'), ('user_reinstated', 'Utilisateur retabli'), ('live_disabled', 'Chaine en direct desactivee'), ('live_enabled', 'Chaine en direct reactivee')], db_index=True, max_length=24)),
                ('object_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('target_repr', models.CharField(blank=True, max_length=255)),
                ('reason', models.TextField(help_text="Obligatoire pour toute action de retrait. C'est ce texte qui est communique a l'auteur du contenu.")),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('affected_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderation_history', to=settings.AUTH_USER_MODEL)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
                ('moderator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderation_actions', to=settings.AUTH_USER_MODEL)),
                ('report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderation_actions', to='engagement.report')),
            ],
            options={
                'verbose_name': 'action de moderation',
                'verbose_name_plural': 'actions de moderation',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['affected_user', '-created_at'], name='moderation__affecte_a717d1_idx'), models.Index(fields=['action', '-created_at'], name='moderation__action_9c4f47_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserSanction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('warning', 'Avertissement'), ('suspension', 'Suspension temporaire'), ('ban', 'Bannissement definitif')], db_index=True, max_length=12)),
                ('reason', models.TextField()),
                ('starts_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Null pour un bannissement definitif ou un avertissement.', null=True)),
                ('lifted_at', models.DateTimeField(blank=True, null=True)),
                ('lifted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sanctions_lifted', to=settings.AUTH_USER_MODEL)),
                ('moderator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sanctions_issued', to=settings.AUTH_USER_MODEL)),
                ('report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sanctions', to='engagement.report')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sanctions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'sanction',
                'verbose_name_plural': 'sanctions',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['user', '-created_at'], name='moderation__user_id_1d9eea_idx')],
            },
        ),
    ]
