# Generated by Django 5.2.17 on 2026-08-11 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Libelle canonique. La traduction affichee vient du frontend, cle 'catalog.category.<slug>'.", max_length=80, verbose_name='nom')),
                ('slug', models.SlugField(help_text='Cle de traduction cote frontend. Ne pas modifier apres creation.', max_length=90, unique=True)),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('icon', models.CharField(blank=True, default='clapperboard', max_length=40)),
                ('accent_color', models.CharField(blank=True, default='#6366f1', help_text='Couleur hexadecimale utilisee sur les pastilles de categorie.', max_length=7)),
                ('display_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'verbose_name': 'categorie',
                'verbose_name_plural': 'categories',
                'ordering': ('display_order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='nom')),
                ('slug', models.SlugField(max_length=60, unique=True)),
                ('usage_count', models.PositiveIntegerField(db_index=True, default=0, help_text='Denormalise pour trier les tags populaires sans agregation.')),
            ],
            options={
                'verbose_name': 'tag',
                'verbose_name_plural': 'tags',
                'ordering': ('-usage_count', 'name'),
            },
        ),
    ]
