# Generated by Django 5.2.17 on 2026-08-11 15:28

import apps.accounts.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True, verbose_name='adresse e-mail')),
                ('username', models.CharField(help_text="Sert d'identifiant public de la chaine (/c/<username>).", max_length=30, unique=True, validators=[django.core.validators.RegexValidator(message='3 a 30 caracteres: minuscules, chiffres, tiret ou underscore, commencant par une lettre ou un chiffre.', regex='^[a-z0-9][a-z0-9_-]{2,29}$')], verbose_name="nom d'utilisateur")),
                ('display_name', models.CharField(blank=True, max_length=80, verbose_name='nom affiche')),
                ('bio', models.TextField(blank=True, max_length=1000, verbose_name='biographie')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/%Y/%m/', verbose_name='avatar')),
                ('role', models.CharField(choices=[('user', 'Utilisateur'), ('moderator', 'Moderateur'), ('admin', 'Administrateur')], db_index=True, default='user', max_length=16, verbose_name='role')),
                ('is_active', models.BooleanField(default=False, help_text='Passe a True apres activation par e-mail.', verbose_name='actif')),
                ('is_staff', models.BooleanField(default=False, verbose_name='acces admin Django')),
                ('is_suspended', models.BooleanField(db_index=True, default=False, verbose_name='suspendu')),
                ('suspension_reason', models.TextField(blank=True, verbose_name='motif de suspension')),
                ('suspended_at', models.DateTimeField(blank=True, null=True)),
                ('preferred_language', models.CharField(choices=[('fr', 'Francais'), ('en', 'English')], default='fr', max_length=5, verbose_name='langue')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'utilisateur',
                'verbose_name_plural': 'utilisateurs',
                'ordering': ('-created_at',),
            },
            managers=[
                ('objects', apps.accounts.models.UserManager()),
            ],
        ),
    ]
