# Generated by Django 5.2.17 on 2026-08-24 13:22

import apps.accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_follower_count_user_following_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='banner',
            field=models.ImageField(blank=True, help_text='Image large affichee en tete de la chaine (16:5 conseille).', null=True, storage=apps.accounts.models.public_profile_storage, upload_to='banners/%Y/%m/', verbose_name='banniere'),
        ),
        migrations.AddField(
            model_name='user',
            name='location',
            field=models.CharField(blank=True, max_length=80, verbose_name='localisation'),
        ),
        migrations.AddField(
            model_name='user',
            name='website_url',
            field=models.URLField(blank=True, verbose_name='site web'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, storage=apps.accounts.models.public_profile_storage, upload_to='avatars/%Y/%m/', verbose_name='avatar'),
        ),
    ]
