# Generated by Django 5.2.17 on 2026-08-31 19:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_banner_user_location_user_website_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(choices=[('google', 'Google')], max_length=20, verbose_name='fournisseur')),
                ('subject', models.CharField(help_text='Identifiant stable du compte chez le fournisseur (`sub`).', max_length=255, verbose_name='identifiant fournisseur')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='e-mail fournisseur')),
                ('last_used_at', models.DateTimeField(blank=True, null=True, verbose_name='derniere utilisation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_accounts', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur')),
            ],
            options={
                'verbose_name': 'compte externe',
                'verbose_name_plural': 'comptes externes',
                'constraints': [models.UniqueConstraint(fields=('provider', 'subject'), name='uniq_social_provider_subject'), models.UniqueConstraint(fields=('provider', 'user'), name='uniq_social_provider_user')],
            },
        ),
    ]
