# Generated by Django 5.2.17 on 2026-08-11 22:43

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('videos', '0002_video_search_vector_video_video_search_vector_gin'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80, verbose_name='nom')),
                ('slug', models.SlugField(max_length=90, unique=True)),
                ('description', models.TextField(blank=True)),
                ('price', models.PositiveIntegerField(help_text='Entier, en FCFA. Jamais un flottant.', verbose_name='prix (FCFA)')),
                ('billing_period', models.CharField(choices=[('monthly', 'Mensuel'), ('quarterly', 'Trimestriel'), ('yearly', 'Annuel')], default='monthly', max_length=12)),
                ('ad_free', models.BooleanField(default=True, help_text='Les abonnes ne voient aucune publicite.')),
                ('benefits', models.JSONField(blank=True, default=list, help_text="Liste de libelles affiches sur la page d'abonnement.")),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': "formule d'abonnement",
                'verbose_name_plural': "formules d'abonnement",
                'ordering': ('display_order', 'price'),
            },
        ),
        migrations.CreateModel(
            name='AdCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('advertiser_name', models.CharField(max_length=120, verbose_name='annonceur')),
                ('title', models.CharField(max_length=200, verbose_name='titre')),
                ('creative', models.FileField(help_text='Image (JPG/PNG/WebP) ou video courte (MP4).', upload_to='ads/%Y/%m/', verbose_name='creative')),
                ('creative_is_video', models.BooleanField(default=False)),
                ('click_url', models.URLField(blank=True, verbose_name='lien de destination')),
                ('placement', models.CharField(choices=[('pre_roll', 'Avant la video'), ('mid_roll', 'Pendant la video')], default='pre_roll', max_length=12)),
                ('duration_seconds', models.PositiveIntegerField(default=10, help_text="Duree d'affichage. Pour une image, duree imposee; pour une video, duree maximale.")),
                ('skippable_after_seconds', models.PositiveIntegerField(default=5, help_text='0 = non ignorable.')),
                ('mid_roll_position', models.FloatField(default=0.5, help_text='0.5 = a la moitie de la video. Ignore pour un pre-roll.')),
                ('start_date', models.DateTimeField(db_index=True)),
                ('end_date', models.DateTimeField(db_index=True)),
                ('impression_cap', models.PositiveIntegerField(default=0, help_text='0 = illimite.')),
                ('impression_count', models.PositiveIntegerField(default=0)),
                ('completed_count', models.PositiveIntegerField(default=0)),
                ('click_count', models.PositiveIntegerField(default=0)),
                ('weight', models.PositiveSmallIntegerField(default=1, help_text="Poids relatif dans la rotation. Un poids 3 est servi trois fois plus souvent qu'un poids 1.")),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('active', 'Active'), ('paused', 'En pause'), ('ended', 'Terminee')], db_index=True, default='draft', max_length=10)),
                ('categories', models.ManyToManyField(blank=True, help_text='Vide = toutes les categories.', related_name='ad_campaigns', to='catalog.category')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ad_campaigns', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'campagne publicitaire',
                'verbose_name_plural': 'campagnes publicitaires',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='AdImpression',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_key', models.CharField(blank=True, max_length=64)),
                ('placement', models.CharField(choices=[('pre_roll', 'Avant la video'), ('mid_roll', 'Pendant la video')], max_length=12)),
                ('played_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('completed', models.BooleanField(db_index=True, default=False)),
                ('skipped', models.BooleanField(default=False)),
                ('watched_seconds', models.PositiveIntegerField(default=0)),
                ('clicked', models.BooleanField(default=False)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impressions', to='monetization.adcampaign')),
                ('video', models.ForeignKey(blank=True, help_text='Contenu contre lequel la publicite a ete diffusee.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ad_impressions', to='videos.video')),
                ('viewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ad_impressions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'impression publicitaire',
                'verbose_name_plural': 'impressions publicitaires',
                'ordering': ('-played_at',),
            },
        ),
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'En attente de paiement'), ('active', 'Actif'), ('cancelled', 'Annule'), ('expired', 'Expire')], db_index=True, default='pending', max_length=12)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('current_period_end', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('auto_renew', models.BooleanField(default=True)),
                ('renewal_failures', models.PositiveSmallIntegerField(default=0)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='monetization.subscriptionplan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'abonnement',
                'verbose_name_plural': 'abonnements',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('orange_money', 'Orange Money'), ('moov_money', 'Moov Money'), ('wave', 'Wave'), ('card', 'Carte bancaire'), ('mock', 'Simulateur (developpement)')], db_index=True, max_length=20)),
                ('type', models.CharField(choices=[('subscription', 'Souscription'), ('renewal', 'Renouvellement')], default='subscription', max_length=16)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('completed', 'Complete'), ('failed', 'Echoue'), ('cancelled', 'Annule')], db_index=True, default='pending', max_length=12)),
                ('amount', models.PositiveIntegerField(help_text='Entier, en FCFA.', validators=[django.core.validators.MinValueValidator(1)], verbose_name='montant (FCFA)')),
                ('currency', models.CharField(default='XOF', max_length=3)),
                ('idempotency_key', models.CharField(db_index=True, help_text="Contrainte d'unicite en base: c'est elle qui empeche un double paiement, pas une verification applicative.", max_length=80, unique=True)),
                ('provider_reference', models.CharField(blank=True, db_index=True, max_length=120)),
                ('payer_identifier', models.CharField(blank=True, help_text='Numero mobile money ou 4 derniers chiffres de la carte. Jamais un PAN complet.', max_length=64)),
                ('failure_reason', models.TextField(blank=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('provider_payload', models.JSONField(blank=True, default=dict)),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='monetization.subscriptionplan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to=settings.AUTH_USER_MODEL)),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='monetization.usersubscription')),
            ],
            options={
                'verbose_name': 'transaction',
                'verbose_name_plural': 'transactions',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('orange_money', 'Orange Money'), ('moov_money', 'Moov Money'), ('wave', 'Wave'), ('card', 'Carte bancaire'), ('mock', 'Simulateur (developpement)')], max_length=20)),
                ('event_id', models.CharField(max_length=120)),
                ('event_type', models.CharField(blank=True, max_length=60)),
                ('payload', models.JSONField(default=dict)),
                ('signature_valid', models.BooleanField(default=False)),
                ('processed', models.BooleanField(db_index=True, default=False)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('processing_error', models.TextField(blank=True)),
                ('received_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='webhook_events', to='monetization.transaction')),
            ],
            options={
                'verbose_name': 'evenement webhook',
                'verbose_name_plural': 'evenements webhook',
                'ordering': ('-received_at',),
            },
        ),
        migrations.AddIndex(
            model_name='adcampaign',
            index=models.Index(fields=['status', 'start_date', 'end_date'], name='monetizatio_status_41a8ef_idx'),
        ),
        migrations.AddIndex(
            model_name='adimpression',
            index=models.Index(fields=['campaign', '-played_at'], name='monetizatio_campaig_62f7b1_idx'),
        ),
        migrations.AddIndex(
            model_name='adimpression',
            index=models.Index(fields=['video', '-played_at'], name='monetizatio_video_i_1b6148_idx'),
        ),
        migrations.AddIndex(
            model_name='usersubscription',
            index=models.Index(fields=['status', 'current_period_end'], name='monetizatio_status_f6fc67_idx'),
        ),
        migrations.AddConstraint(
            model_name='usersubscription',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['pending', 'active'])), fields=('user',), name='uniq_open_subscription_per_user'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['user', '-created_at'], name='monetizatio_user_id_8eab87_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['status', '-created_at'], name='monetizatio_status_5e62d0_idx'),
        ),
        migrations.AddConstraint(
            model_name='webhookevent',
            constraint=models.UniqueConstraint(fields=('provider', 'event_id'), name='uniq_webhook_event_per_provider'),
        ),
    ]
