# Generated by Django 5.2.17 on 2026-08-12 07:00

import apps.monetization.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monetization', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adcampaign',
            name='creative',
            field=models.FileField(help_text='Image (JPG/PNG/WebP) ou video courte (MP4). Stockee dans le bucket public: une creative est vue par tous les spectateurs.', storage=apps.monetization.models.public_creative_storage, upload_to='ads/%Y/%m/', verbose_name='creative'),
        ),
    ]
